# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd837a8a53dcb8ca3e422af3602182d98130764670901d00f4a96d1751ba9fe73498ba5db26341ae2269675fc07903b0c742b3df109a64c27815d8b1cb737a7b

test:
  secret_key_base: bc324fc0c17ac88b39c9b2b66ae5eb21e90f840fe1db3855f4727186bd9c5ec0e8fa60d5160001e50bf0457195fcb7093b113ccca5e372b5af0e8743ec669a13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
